---
title: "Peskas data description"
date: "Uploaded on `r Sys.time()`"
output: html_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, echo = FALSE)
```

### Introductory information

This repository contains trips and catch data related to the Peskas project.
* Format of the files
* Relationship between the files
* Name/institution/address/email information for Principle investigator (or person responsible for collecting the data), Associate or co-investigators, Contact person for questions
* Date of data collection (can be a single date, or a range)
* Information about geographic location of data collection
* Keywords used to describe the data topic
* Temporal (`r time_range`) and geographic info 

### Methodological information

* Method description, links or references to publications or other documentation containing experimental design or
protocols used in data collection
* Any instrument-specific information needed to understand or interpret the data
* Describe any quality-assurance procedures performed on the data
* Definitions of codes or symbols 
* People involved with sample collection, processing, analysis and/or submission

### Data specific information

* Full names and definitions (spell out abbreviated words) of column headings for tabular data
* Units of measurement
* Definitions for codes or symbols used to record missing data
* Specialized formats or abbreviations used

### Sharing and Access information

* Licenses or restrictions placed on the data
* Links to publications that cite or use the data
* Links to other publicly accessible locations of the data
* Recommended citation for the data
* Information about funding sources that supported the collection of the data
