name: Generate and upload form summary report

on:
  schedule:
    - cron:  '0 0 1 * *'

env:
  GCP_SA_KEY: ${{ secrets.PESKAS_DATAINGESTION_GCS_KEY }}

jobs:

  build-container:
    name: Build R container
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build image with cache
        id: build-docker
        uses: whoan/docker-build-with-cache-action@v5
        with:
          username: $GITHUB_ACTOR
          password: "${{ secrets.GITHUB_TOKEN }}"
          registry: docker.pkg.github.com
          image_name: r-runner-peskas-timor
          dockerfile: Dockerfile.prod

  form-summary:
    name: Generate form summary
    needs: [build-container]
    runs-on: ubuntu-22.04
    container:
      image: docker.pkg.github.com/worldfishcenter/peskas.timor.data.pipeline/r-runner-peskas-timor
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Set env to production
        if: endsWith(github.ref, '/main')
        run: echo "R_CONFIG_ACTIVE=production" >> $GITHUB_ENV
      - name: Generate and upload form summary
        run: Rscript -e 'source(system.file("report/generate_form_summary.R", package = "peskas.timor.data.pipeline"))'
