name: Send landing sites activity report

on:
  schedule:
    - cron:  '0 */2 * * *'

env:
  PESKAS_GMAIL_KEY: ${{ secrets.PESKAS_GMAIL_KEY }}

jobs:

  build-container:
    name: Build R container
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build image with cache
        id: build-docker
        uses: whoan/docker-build-with-cache-action@v5
        with:
          username: $GITHUB_ACTOR
          password: "${{ secrets.GITHUB_TOKEN }}"
          registry: docker.pkg.github.com
          image_name: r-runner-peskas-timor
          dockerfile: Dockerfile.prod

  send-mail:
    name: Send activity report
    needs: [build-container]
    runs-on: ubuntu-20.04
    container:
      image: docker.pkg.github.com/worldfishcenter/peskas.timor.data.pipeline/r-runner-peskas-timor
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Set env to production
        if: endsWith(github.ref, '/main')
        run: echo "R_CONFIG_ACTIVE=production" >> $GITHUB_ENV
      - name: Call send_sites_report()
        run: Rscript -e 'peskas.timor.data.pipeline::send_sites_report()'
